# Adopt version 2 syntax:
version: '2'

volumes:
    database_data:
        driver: local

services:
# Setup the Nginx container
###########################
    web01:
        image: nginx:1.14
        container_name: lemp-web01
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        labels:
          - "traefik.port=80"
          - "traefik.backend=nginx-cluster"
          - "traefik.frontend.rule=Host:nginx.somostinn.com.ve"
    web02:
        image: nginx:1.14
        container_name: lemp-web02
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        labels:
          - "traefik.port=80"
          - "traefik.backend=nginx-cluster"
          - "traefik.frontend.rule=Host:nginx.somostinn.com.ve"
    web03:
        image: nginx:1.14
        container_name: lemp-web03
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        labels:
          - "traefik.port=80"
          - "traefik.backend=nginx-cluster"
          - "traefik.frontend.rule=Host:nginx.somostinn.com.ve"

# Setup the PHP container
###########################
    php:
        build: ./docker/php/
        image: lemp/php
        container_name: lemp-php
        expose:
            - 9000
        volumes:
            - ./www:/var/www/html
        links:
            - mysql
        labels:
          - "traefik.enable=false"

# Setup the Database (MySQL) container
###########################
    mysql:
        image: mysql:5.7
        container_name: lemp-mysql
        volumes:
            - database_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: project
            MYSQL_USER: project
            MYSQL_PASSWORD: project
        labels:
          - "traefik.enable=false"

# Setup the phpmyadmin container
###########################
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: lemp-pma
        restart: always
        links:
          - mysql
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: secret
          PMA_ARBITRARY: 1
        labels:
          - "traefik.port=80"
          - "traefik.frontend.rule=Host:pma.somostinn.com.ve"

# Setup the traefik Proxy/LB container
###########################
    traefik:
      image: traefik:v1.7.4
      container_name: lemp-traefik
      command: --web --docker --docker.domain=somostinn.com.ve --logLevel=DEBUG
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml
      labels:
        - "traefik.frontend.rule=Host:traefik.somostinn.com.ve"
        - "traefik.port=8080"
